from address import Address


class Trials(object):
    def __init__(self):
        self.trial_id = ""
        self.trial_title = ""
        self.trial_acronym = ""
        self.trial_url = ""
        self.summary_lay = ""
        self.summary_sci = ""
        self.org_data = ""
        self.secondary_ids = ""
        self.health_Condition = ""
        self.interventions = ""
        self.characteristics = ""
        self.outcome_prim = ""
        self.outcome_sec = ""
        self.countries_recruitment = ""
        self.locations_recruitment = ""
        self.recruitment = ""
        self.criteria_inclusion = ""
        self.criteria_inclusion_add = ""
        self.criteria_exclusion = ""
        self.add_prim_sponsor = ""
        self.add_sci_queries = ""
        self.add_pub_queries = ""
        self.add_mat_support = ""
        self.status = ""
        self.publications = ""
